"""Initial post model

Revision ID: aca7e8e90b26
Revises:
Create Date: 2025-03-31 21:12:16.739973

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "aca7e8e90b26"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_post_creator_id"), "post", ["creator_id"], unique=False)
    op.create_index(op.f("ix_post_title"), "post", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_title"), table_name="post")
    op.drop_index(op.f("ix_post_creator_id"), table_name="post")
    op.drop_table("post")
    # ### end Alembic commands ###
